---
- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openssh
    - seahorse

- name: Create .ssh directory
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: 0700

- name: Copy public SSH keys to .ssh directory
  copy:
    src: "{{ dotfiles_home }}/playbooks/roles/ssh/files/{{ item }}"
    dest: "{{ user_home }}/.ssh/{{ item }}"
    force: yes
    mode: 0700
  with_items:
    - id_rsa

- name: Get remote URL in repository "dotfiles"
  command: git remote get-url origin
  args:
    chdir: "{{ dotfiles_home }}"
  register: dotfiles_url
  changed_when: False

- name: Change remote URL from HTTPS to SSH in repository "dotfiles"
  command: git remote set-url origin git@github.com:{{ git_user }}/dotfiles.git
  args:
    chdir: "{{ dotfiles_home }}"
  changed_when: dotfiles_url.stdout | search("http")
