---
- name: git | Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: git | Symlink config
  file:
    src: ~/dotfiles/git/gitconfig
    dest: ~/.gitconfig
    force: yes
    state: link
...
