---
- name: pacman | Refresh package list and upgrade whole system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install vim
  become: true
  pacman:
    name: vim
    state: latest
...
