engines:
  vint:
    enabled: true
  shellcheck:
    enabled: true
  reek:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        python:
ratings:
  paths:
    - "launch"
    - "bootstrap"
    - "x/.xinitrc"
    - "shell/.zshrc"
    - "**.sh"
    - "**.vim"
    - "**.md"
    - "**.rb"
    - "**.py"
    - "bin/**"
