---
- name: Install packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - lxappearance

- name: Create directory
  file:
    path: "{{ fonts_home }}"
    state: directory

- name: Download patched NERD fonts
  get_url:
    url: http://www.roemisch-drei.de/fonts.zip
    dest: "{{ fonts_home }}/nerd-fonts.zip"

- name: Unarchive patched NERD fonts
  unarchive:
    src: "{{ fonts_home }}/nerd-fonts.zip"
    dest: "{{ fonts_home }}"
