---
- name: Install packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - lxappearance

- name: Create directory
  file:
    path: "{{ fonts_home }}"
    state: directory

- name: Download fonts
  get_url:
    url: "http://www.roemisch-drei.de/{{ fonts_tar }}"
    dest: "{{ fonts_home }}/{{ fonts_tar }}"

- name: Unarchive fonts
  unarchive:
    src: "{{ fonts_home }}/{{ fonts_tar }}"
    dest: "{{ fonts_home }}"

- name: Symlink fonts
  # become: yes
  file:
    src: "{{ fonts_home }}/patched-fonts/fonts/SFDisplay/{{ item }}"
    dest: "~/.fonts/patched-fonts/{{ item }}"
    state: link
  with_items:
    - "SFDisplay-Regular.otf"
    # sudo mv -f /tmp/fonts/fonts/patched-fonts/**/*.otf /usr/share/fonts/OTF
