---
- name: Install packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - expac
    - yajl

- name: Download packages
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: "{{ aur_home }}/{{ item }}"
    force: yes
  register: repos
  with_items:
    - cower
    - pacaur

- name: Build packages
  changed_when: item | changed
  command: makepkg PKGBUILD --install --skippgpcheck
  args:
    chdir: "{{ aur_home }}/{{ item.item }}"
  with_items: "{{ repos.results }}"
  loop_control:
    label: "{{ item.item }}"
